### ISSUE TITLE
mapFile outside specification

### ISSUE THREAD

**Issue by layernull** [akhoury/RedirectBB#1]
There seems to be a minor problem with the parsing of the mapFile path, probable cause is the following code line in redirect.js

```
mapFile = path.normalize(argv.m || argv.map || __dirname + '/map.sample.json'),
```

preventing outside configuration of the mapFile name via a systemd.service. systemd gave the following error, irregardless if I set an absolute path or the filename.

```
● redirectbb.service - RedirectBB
Loaded: loaded (/etc/systemd/system/redirectbb.service; disabled)
Active: failed (Result: exit-code) since Sun 2016-01-24 12:54:38 EST; 5s ago
Process: 1662 ExecStart=/usr/bin/node redirect.js --map="/home/<user>/RedirectBB/map.json" --   port=3000 --host=127.0.0.1 –verbose (code=exited, status=1/FAILURE)
Main PID: 1662 (code=exited, status=1/FAILURE)

    Jan 24 12:54:38 redirectbb[1662]: at Object.<anonymous>        (/home/<user>/RedirectBB/redirect.js:76:11)
Jan 24 12:54:38 redirectbb[1662]: at Module._compile (module.js:460:26)
Jan 24 12:54:38 redirectbb[1662]: at Object.Module._extensions..js (module.js:478:10)
Jan 24 12:54:38 redirectbb[1662]: at Module.load (module.js:355:32)
Jan 24 12:54:38 redirectbb[1662]: at Function.Module._load (module.js:310:12)
Jan 24 12:54:38 redirectbb[1662]: at Function.Module.runMain (module.js:501:10)
Jan 24 12:54:38 redirectbb[1662]: at startup (node.js:129:16)
Jan 24 12:54:38 redirectbb[1662]: at node.js:814:3
Jan 24 12:54:38 systemd[1]: redirectbb.service: main process exited, code=exited, status=1/FAILURE
Jan 24 12:54:38 systemd[1]: Unit redirectbb.service entered failed state. 
```

Easy fix: Replace above line with 

```
mapFile = 'map.json',
```

Thank you for writing this helpful Redirector!

**Comment by akhoury** [comment]
I guess i could rename the sample to `map.json` but honestly I am not really maintaining this module, I think you achieve better results by using an Nginx Https Module

http://nginx.org/en/docs/http/ngx_http_map_module.html

http://serverfault.com/questions/441235/maintaining-redirects-in-nginx-from-an-external-source/441517#441517

read https://github.com/akhoury/nodebb-plugin-import#imported-now-what

> `redirect.map.csv` same data as the json, but in csv, probably what you need for the nginx map module, (example here, you probably need to find/replace all commas with a space)

**Comment by layernull** [comment]
No worries! The nginx service is running anyway, I agree Nginx Https Module is thus the way to go for the long run.
To start off with, RedirectBB works nicely though. Will take a look at the links you provided, thanks!

I will close this as "won't fix". :) Is really minor anyhow, easy workarounds exist.
